@sandtableUrl = http://sandtisch-led.local

### Playlist on
POST {{sandtableUrl}}/json/state
Content-Type: application/json

{
    "Sandtable": {
        "IsPlaylistActive": true
    }
}

### Playlist off
POST {{sandtableUrl}}/json/state
Content-Type: application/json

{
    "Sandtable": {
        "IsPlaylistActive": false
    }
}

### Set playlist
POST {{sandtableUrl}}/json/state
Content-Type: application/json

{
    "Sandtable": {
        "Playlist": [
            {
                "Filepath": "sdcard/Hexagons.gcode",
                "PresetId": 1,
                "EraseAfter": false
            },
            {
                "Filepath": "sdcard/Jonah_Herz.gcode",
                "PresetId": 2,
                "EraseAfter": false
            },
            {
                "Filepath": "sdcard/Eraser/Kringel.gcode",
                "PresetId": 3,
                "EraseAfter": false
            },
            {
                "Filepath": "sdcard/Michael.gcode",
                "PresetId": 4,
                "EraseAfter": false
            },
            {
                "Filepath": "sdcard/Eraser/Space Filler.gcode",
                "PresetId": 5,
                "EraseAfter": false
            },
            {
                "Filepath": "sdcard/Jonah.gcode",
                "PresetId": 6,
                "EraseAfter": false
            }
        ]
    }
}

### Set playlist for MakerFaire
POST {{sandtableUrl}}/json/state
Content-Type: application/json

{
    "Sandtable": {
        "Playlist": [
            {
                "Filepath": "sdcard/MakerSpace/MSM-Logo_outline_MakerFaire.gcode",
                "PresetId": 12,
                "EraseAfter": false
            },
            {
                "Filepath": "sdcard/Eraser/MSM-Eraser.gcode",
                "PresetId": 13,
                "EraseAfter": false
            },
            {
                "Filepath": "sdcard/MakerSpace/MSM-Logo_outline_MakerFaire.gcode",
                "PresetId": 14,
                "EraseAfter": false
            },
            {
                "Filepath": "sdcard/Eraser/MSM-Eraser.gcode",
                "PresetId": 15,
                "EraseAfter": false
            },
            {
                "Filepath": "sdcard/MakerSpace/MSM-Logo_outline_MakerFaire.gcode",
                "PresetId": 16,
                "EraseAfter": false
            },
            {
                "Filepath": "sdcard/Eraser/MSM-Eraser.gcode",
                "PresetId": 17,
                "EraseAfter": false
            }
        ]
    }
}